### ISSUE TITLE
Invalid search id mid-acquisition - Our end or TikTok?

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [CybersecurityForDemocracy/tiktok-library#89]
Obtained error

```
{"error":{"code":"invalid_params","message":"Invalid count or cursor","log_id":"20241009180101BDD8B4B0A88D600D1801"}}'
```

while running

`hatch run tiktok-lib run --include-any-hashtags war 20231108 20231108 --debug --raw-responses-output-dir debugging-folder --db-file debugging.db --region US` 

Unsure if really an issue on our end or just TikTok not properly keeping track of their cursos

**Comment by macpd** [comment]
I ran into this a lot, and looked into it. AFAIK it’s a big in the API.

**Comment by BrunoGomesCoelho** [comment]
Thanks! Also just saw the comment about `Often the API gets overloaded and returns 500 (which still consumes request quota) if the query returns lots of videos and the date range is large.`

Did you find using any longer (like minutes to hours) waits before time-out helped or unsure?

**Comment by macpd** [comment]
I didn’t do an in depth investigation. Just decided to use smaller time
frames when I realized it worked better

**Comment by BrunoGomesCoelho** [comment]
Got it, thanks! 

We'll investigate some longer times,[ we're getting 500s](https://github.com/CybersecurityForDemocracy/tiktok-library/issues/90) even with single-day, single-unpopular hashtags queries.

**Comment by BrunoGomesCoelho** [comment]
See #90 for frequent 500 errors
